-- ============================================
-- Expand TECH_REGISTRY (50+ technologies)
-- ============================================
INSERT INTO public.tech_registry (slug, name, color, category) VALUES
  ('react', 'React', '#61DAFB', 'frontend'),
  ('nextdotjs', 'Next.js', '#000000', 'frontend'),
  ('vuedotjs', 'Vue.js', '#4FC08D', 'frontend'),
  ('svelte', 'Svelte', '#FF3E00', 'frontend'),
  ('astro', 'Astro', '#BC52EE', 'frontend'),
  ('remix', 'Remix', '#000000', 'frontend'),
  ('angular', 'Angular', '#DD0031', 'frontend'),
  ('solid', 'SolidJS', '#2C4F7C', 'frontend'),
  ('typescript', 'TypeScript', '#3178C6', 'language'),
  ('javascript', 'JavaScript', '#F7DF1E', 'language'),
  ('python', 'Python', '#3776AB', 'language'),
  ('go', 'Go', '#00ADD8', 'language'),
  ('rust', 'Rust', '#000000', 'language'),
  ('php', 'PHP', '#777BB4', 'language'),
  ('ruby', 'Ruby', '#CC342D', 'language'),
  ('nodedotjs', 'Node.js', '#5FA04E', 'backend'),
  ('deno', 'Deno', '#000000', 'backend'),
  ('bun', 'Bun', '#FBF0DF', 'backend'),
  ('express', 'Express', '#000000', 'backend'),
  ('nestjs', 'NestJS', '#E0234E', 'backend'),
  ('django', 'Django', '#092E20', 'backend'),
  ('flask', 'Flask', '#000000', 'backend'),
  ('fastapi', 'FastAPI', '#009688', 'backend'),
  ('rubyonrails', 'Rails', '#D30001', 'backend'),
  ('laravel', 'Laravel', '#FF2D20', 'backend'),
  ('spring', 'Spring', '#6DB33F', 'backend'),
  ('postgresql', 'PostgreSQL', '#4169E1', 'database'),
  ('mysql', 'MySQL', '#4479A1', 'database'),
  ('mongodb', 'MongoDB', '#47A248', 'database'),
  ('redis', 'Redis', '#DC382D', 'database'),
  ('sqlite', 'SQLite', '#003B57', 'database'),
  ('supabase', 'Supabase', '#3FCF8E', 'backend'),
  ('firebase', 'Firebase', '#DD2C00', 'backend'),
  ('prisma', 'Prisma', '#2D3748', 'database'),
  ('drizzle', 'Drizzle', '#C5F74F', 'database'),
  ('graphql', 'GraphQL', '#E10098', 'api'),
  ('apollographql', 'Apollo', '#311C87', 'api'),
  ('trpc', 'tRPC', '#2596BE', 'api'),
  ('docker', 'Docker', '#2496ED', 'devops'),
  ('kubernetes', 'Kubernetes', '#326CE5', 'devops'),
  ('amazonwebservices', 'AWS', '#FF9900', 'cloud'),
  ('googlecloud', 'GCP', '#4285F4', 'cloud'),
  ('microsoftazure', 'Azure', '#0078D4', 'cloud'),
  ('vercel', 'Vercel', '#000000', 'cloud'),
  ('netlify', 'Netlify', '#00C7B7', 'cloud'),
  ('cloudflare', 'Cloudflare', '#F38020', 'cloud'),
  ('tailwindcss', 'Tailwind', '#06B6D4', 'styling'),
  ('sass', 'Sass', '#CC6699', 'styling'),
  ('styledcomponents', 'Styled', '#DB7093', 'styling'),
  ('framer', 'Framer Motion', '#0055FF', 'animation'),
  ('greensock', 'GSAP', '#88CE02', 'animation'),
  ('threedotjs', 'Three.js', '#000000', 'graphics'),
  ('webgl', 'WebGL', '#990000', 'graphics'),
  ('blender', 'Blender', '#F5792A', 'graphics'),
  ('figma', 'Figma', '#F24E1E', 'design'),
  ('adobexd', 'Adobe XD', '#FF61F6', 'design'),
  ('vite', 'Vite', '#646CFF', 'tooling'),
  ('webpack', 'Webpack', '#8DD6F9', 'tooling'),
  ('git', 'Git', '#F05032', 'tooling'),
  ('github', 'GitHub', '#181717', 'tooling'),
  ('gitlab', 'GitLab', '#FC6D26', 'tooling'),
  ('jest', 'Jest', '#C21325', 'testing'),
  ('vitest', 'Vitest', '#6E9F18', 'testing'),
  ('playwright', 'Playwright', '#2EAD33', 'testing'),
  ('cypress', 'Cypress', '#69D3A7', 'testing'),
  ('stripe', 'Stripe', '#635BFF', 'payments'),
  ('paypal', 'PayPal', '#003087', 'payments'),
  ('openai', 'OpenAI', '#412991', 'ai'),
  ('anthropic', 'Anthropic', '#191919', 'ai'),
  ('langchain', 'LangChain', '#1C3C3C', 'ai'),
  ('huggingface', 'HuggingFace', '#FFD21E', 'ai'),
  ('redux', 'Redux', '#764ABC', 'state'),
  ('zustand', 'Zustand', '#443E38', 'state'),
  ('reactquery', 'React Query', '#FF4154', 'state'),
  ('d3dotjs', 'D3.js', '#F9A03C', 'data-viz'),
  ('chartdotjs', 'Chart.js', '#FF6384', 'data-viz')
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
    color = EXCLUDED.color,
    category = EXCLUDED.category,
    is_active = true,
    updated_at = now();

-- ============================================
-- Expand TAG_REGISTRY (30+ tags)
-- ============================================
INSERT INTO public.tag_registry (slug, name, color) VALUES
  ('saas', 'SaaS', '#3B82F6'),
  ('ai', 'AI', '#F59E0B'),
  ('pwa', 'PWA', '#10B981'),
  ('3d', '3D', '#EC4899'),
  ('landing-page', 'Landing Page', '#F97316'),
  ('e-commerce', 'E-commerce', '#EF4444'),
  ('dashboard', 'Dashboard', '#14B8A6'),
  ('mobile', 'Mobile', '#06B6D4'),
  ('web-app', 'Web App', '#6366F1'),
  ('enterprise', 'Enterprise', '#8B5CF6'),
  ('fintech', 'Fintech', '#22C55E'),
  ('healthtech', 'Healthtech', '#0EA5E9'),
  ('edtech', 'EdTech', '#A855F7'),
  ('b2b', 'B2B', '#0891B2'),
  ('b2c', 'B2C', '#DB2777'),
  ('marketplace', 'Marketplace', '#D97706'),
  ('crm', 'CRM', '#7C3AED'),
  ('analytics', 'Analytics', '#0D9488'),
  ('booking', 'Booking', '#F472B6'),
  ('realtime', 'Real-time', '#FB7185'),
  ('automation', 'Automation', '#84CC16'),
  ('cms', 'CMS', '#A78BFA'),
  ('portfolio', 'Portfolio', '#FCD34D'),
  ('blog', 'Blog', '#FBBF24'),
  ('chatbot', 'Chatbot', '#34D399'),
  ('crypto', 'Crypto', '#F7931A'),
  ('iot', 'IoT', '#22D3EE'),
  ('streaming', 'Streaming', '#E11D48'),
  ('social', 'Social', '#1DA1F2'),
  ('productivity', 'Productivity', '#0EA5E9'),
  ('gamedev', 'Game', '#FF4500'),
  ('open-source', 'Open Source', '#10B981'),
  ('api', 'API', '#6366F1'),
  ('design-system', 'Design System', '#EC4899')
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
    color = EXCLUDED.color,
    is_active = true,
    updated_at = now();